CREATE DATABASE IF NOT EXISTS cymdb;
USE ctmdb;
CREATE TABLE category(
	no INT AUTO_INCREMENT,
	name VARCHAR(10),
	PRIMARY KEY (no,name)
);
CREATE TABLE product(
	no INT AUTO_INCREMENT,
	category INT,
	name VARCHAR(10),
	price INT,
	PRIMARY KEY (no,name),
	FOREIGN KEY (category) REFERENCES category (no) ON DELETE CASCADE
);
CREATE TABLE user(
	no INT AUTO_INCREMENT,
	name VARCHAR(10) NOT NULL,
	id VARCHAR(20) NOT NULL,
	password VARCHAR(20) NOT NULL,
	email VARCHAR(30) NOT NULL,
	phone VARCHAR(11) NOT NULL,
	regdate DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(no,id)
);
